### ISSUE TITLE
Error free measurement generation

### ISSUE THREAD

**Issue by landon-the-boyd** [navsquad/navsim#6]
Generating perfect measurement scenarios would assist in algorithm workflow, but navsim/navsim/config.py disallows generation of perfect measurements on line 86

`errors = dc.from_dict(data_class=ErrorConfiguration, data=config.get("errors"))`

**Comment by tannerkoza** [comment]
Went ahead and made this a feature in the lastest commit (forgot to link issue). All you need to do is comment out/remove the error you don't want to simulate in your configuration file and that should work.
